#!/usr/bin/env bash

# Touches the filename provided and makes it executable
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <filename>"
    exit 1
fi

filename="$1"

touch "$filename"
echo "#!/usr/bin/env bash" >> "$filename"
chmod +x "$filename"

echo "BAD TOUCH: $filename 🖕"
