#!/usr/bin/env bash

# Shell script to run grcov on a project.
# https://github.com/mozilla/grcov
#
# Requires grcov be installed.

rustup default nightly

export CARGO_INCREMENTAL=0
export RUSTFLAGS="-Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests -Cpanic=abort"
export RUSTDOCFLAGS="-Cpanic=abort"

cargo clean
cargo build
cargo test

grcov ./target/debug/ -s src -t html --llvm --branch --ignore-not-existing -o ./target/debug/coverage/

open "./target/debug/coverage/index.html"

rustup default stable
